language: python

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
    - python: 3.7-dev
    - python: 3.6-dev

python:
  - '3.6'
  - 3.6-dev
  - 3.7-dev
  - nightly

install:
  - pip install .[dev]
  - pip install coveralls

script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py doc
  - python setup.py sdist
  - python setup.py bdist_wheel

after_success:
  - coveralls

before_deploy:
  - pip install dothub

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: Ovv
    password:
      secure: lldoHkBPyFjcMEWpOMzaXeNdNl1JUgodXfrm9TPT4DYNcQCDU01f6xm8uShBT47mz+tbrUnx2rFhZmTmZAqZDODo7pmkukSrhBRpbLroEp6045MmT4P4aJjoGJooksGouqOsJjqE8yGwyinCVsv0ZNi1RZDxxuUw3Ye+HtDllMNv4XUeEBxOY5LtKpGW/+MF0QZiDggvR2bcLlMJz2EJvtIzhdRtl7fy2eAdrsQoyXhqt7Zuu0y/sc4YTiRt1adLFFFOIDL6mtL76D2eHBQm5oHJM5TtZi0gs633567fyEZ6Gm9fxSo0Ba9L7sen6ApgJLx2yba1+7ititXg7/U7+DvgmFT3Tk294cBRGF/3rhzt60p1xYO1b6tyFK5GTPghidAJZb/OQoMb9L6iZhCmMCukvdW0/241yiLdSQfMbeCzO8diwpwsJiv7k8pWtGTtl2+PtuH26zyZZeuQpu3BlctF5r/hdaiuggoN87RzlOLwqbIRfHZfMGA24LJNbtyRcu3mvaZwFFrRq5NWYqwU2VHQB/plBvB4c+FRyKRIcbiN/G+31WEK3cuMPaKfXM0opJwVpLNA320IHgVxZu0b78Exr2Qs48cBYiEl/BtHYPRYDGscSI5LYZ5cPrGcrhp7Z6jBFTHenq+IW/O21qtxv1h9R9VXyatIGHSW0U/dLOA=
    on:
      repo: pyslackers/slack-sansio
      branch: master
      python: '3.6'
      tags: true
  - provider: script
    script: "yes | dothub repo --owner pyslackers --repository slack-sansio push --input_file .github/.dothub.repo.yml"
    on:
      repo: pyslackers/slack-sansio
      branch: master
      python: '3.6'
