language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

env:
  global: 
    - secure: "XzDel/RxXPXLejpaJju9WzwaWmAmQMgJJ5RXjBavfn9I7X/vPMkzqc1qVKkoG7n0C/k+E3cCxl72MP97z+f70ohzZDKjCFWHzNRpsEh7HBWTSvZCQIyJCB8fi/vRHpvLzDs2VxxnvFxARa037w1opQYN2MRcwziQ+t6KfkEgnDfWfabIphnsuL+Iv88zr2CZEKIlhdkkAh1jil98/kNaJQglknHIlAEYFwHPi9dMWfsX2w3dEPgpnUOsMdVcqUfjwT0fZ8mmK7tdKI9rfnKqCWl0g1ZHlLw1DOSXxajZdJK5Zjf2eUz5vXSCzpz1zev6zpk/n5PVN820CVDfrOnq826fD5SC9oxgVEeuAdxkwLxuEcXrdDFPBn3LC3hZY4fJjn0M1SKreIcOP4QmOxCb62MaA2QEjOMZz+HwzoRTS/cqM0qR7Rw17ufMKN9ThqcJxT0AkkvvldqZ3mekKCrrHxgl2WqW2yw6i3pF/WmQik+EgWLBlBI3El5YlqEEpPWHZSW3KyATMHkoBsMwO1w++ATisDDpQKO52uXgMEcuAPVAOcb/bjbuRNm5dyfyuQbzCWQE8HYo84aKRCu9O+V53Bvf/BiO+zMNL6u3IqAkwbka713BSuH038Vu14Ir3lCe0PvU4/MnuuPzC3Y37mdK2qmNE2QXbuZ/ZgMmGKB6cjA="

install:
  - pip install poetry tox
  - poetry install
  - pip install tox-travis

script:
  - if [[ $TRAVIS_PYTHON_VERSION = "3.7" ]];
    then
      poetry run slack/tests/test.sh;
    else
      poetry run pytest test --verbose --cov;
    fi

after_success:
  - coveralls

deploy:
  - provider: script
    script: poetry publish --username Ovv --password $PYPI_PASS --build
    on:
      repo: pyslackers/slack-sansio
      branch: master
      python: '3.7'
      tags: true
